@startuml

title __DTOS's Class Diagram__\n

  namespace com.vrush.microservices.financial {
    namespace dtos {
      class com.vrush.microservices.financial.dtos.PaymentAnalyzedDTO {
          - idBooking : UUID
          + PaymentAnalyzedDTO()
          + PaymentAnalyzedDTO()
          + equals()
          + getIdBooking()
          + getState()
          + hashCode()
          + setIdBooking()
          + setState()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.vrush.microservices.financial {
    namespace dtos {
      class com.vrush.microservices.financial.dtos.TransactionDTO {
          - analysis : String
          - creationDate : LocalDateTime
          - id : UUID
          - idBooking : UUID
          - lastUpdate : LocalDateTime
          - totalValue : BigDecimal
          + TransactionDTO()
          + TransactionDTO()
          + TransactionDTO()
          {static} + builder()
          + equals()
          + getAnalysis()
          + getCreationDate()
          + getId()
          + getIdBooking()
          + getLastUpdate()
          + getTotalValue()
          + hashCode()
          + setAnalysis()
          + setCreationDate()
          + setId()
          + setIdBooking()
          + setLastUpdate()
          + setTotalValue()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.vrush.microservices.financial {
    namespace dtos {
      class com.vrush.microservices.financial.dtos.TransactionDTO.TransactionDTOBuilder {
          - analysis : String
          - creationDate : LocalDateTime
          - id : UUID
          - idBooking : UUID
          - lastUpdate : LocalDateTime
          - totalValue : BigDecimal
          + analysis()
          + build()
          + creationDate()
          + id()
          + idBooking()
          + lastUpdate()
          + toString()
          + totalValue()
          ~ TransactionDTOBuilder()
      }
    }
  }
  

  com.vrush.microservices.financial.dtos.PaymentAnalyzedDTO .up.|> java.io.Serializable
  com.vrush.microservices.financial.dtos.PaymentAnalyzedDTO o-- com.vrush.microservices.financial.enums.BookingStateEnum : state
  com.vrush.microservices.financial.dtos.TransactionDTO +-down- com.vrush.microservices.financial.dtos.TransactionDTO.TransactionDTOBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
