@startuml

title __CONFIG's Class Diagram__\n

  namespace com.vrush.microservices.consumer {
    namespace config {
      class com.vrush.microservices.consumer.config.CommonJoinPointConfig {
          + trackMethod()
      }
    }
  }
  

  namespace com.vrush.microservices.consumer {
    namespace config {
      class com.vrush.microservices.consumer.config.FeignConfiguration {
          + errorDecoder()
          + pageJacksonModule()
          + retryer()
      }
    }
  }
  

  namespace com.vrush.microservices.consumer {
    namespace config {
      class com.vrush.microservices.consumer.config.FeignErrorDecoder {
          + decode()
      }
    }
  }
  

  namespace com.vrush.microservices.consumer {
    namespace config {
      class com.vrush.microservices.consumer.config.FeignRetryer {
          - attempt : int
          {static} - log : Logger
          - maxAttempts : int
          - maxPeriod : long
          - period : long
          + FeignRetryer()
          + FeignRetryer()
          + clone()
          + continueOrPropagate()
          - currentTimeMillis()
          - nextMaxInterval()
      }
    }
  }
  

  namespace com.vrush.microservices.consumer {
    namespace config {
      class com.vrush.microservices.consumer.config.TrackMethodAnnotationAspect {
          - environment : Environment
          {static} - log : Logger
          + TrackMethodAnnotationAspect()
          + trackMethod()
      }
    }
  }
  

  com.vrush.microservices.consumer.config.FeignErrorDecoder .up.|> feign.codec.ErrorDecoder
  com.vrush.microservices.consumer.config.FeignRetryer .up.|> feign.Retryer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
